server: 
  port: 9002
spring: 
  application:  
    name:  tensquare_recruit-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_recruit?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
